# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alloy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('balance', models.CharField(blank=True, default='Ni', max_length=3, verbose_name='Баланс')),
                ('type_of_alloy', models.CharField(blank=True, max_length=70)),
                ('type_of_structure', models.CharField(blank=True, max_length=70)),
                ('work_temp', models.IntegerField(blank=True, null=True, verbose_name='Рабочая температура')),
            ],
            options={
                'verbose_name_plural': 'жаропрочные сплавы',
                'verbose_name': 'жаропрочный сплав',
            },
        ),
        migrations.CreateModel(
            name='AlloyingElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=10, verbose_name='Элемент')),
                ('value', models.FloatField()),
                ('alloy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nickel_super_alloys.Alloy', verbose_name='Сплав')),
            ],
            options={
                'verbose_name_plural': 'легирующие элементы',
                'verbose_name': 'легирующий элемент',
            },
        ),
        migrations.CreateModel(
            name='LongTimeStressRupture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='Температура, С')),
                ('life', models.IntegerField(verbose_name='Время испытания, ч')),
                ('stress', models.IntegerField(verbose_name='Предел длительной прочности, МПа')),
                ('alloy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nickel_super_alloys.Alloy', verbose_name='Сплав')),
            ],
            options={
                'verbose_name_plural': 'длительные прочности',
                'verbose_name': 'длительная прочность',
                'ordering': ['temperature'],
            },
        ),
        migrations.CreateModel(
            name='OtherProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('alloy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nickel_super_alloys.Alloy', verbose_name='Сплав')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
